/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as VerifyImport } from './routes/verify'
import { Route as LoginImport } from './routes/login'
import { Route as DashboardImport } from './routes/dashboard'
import { Route as ApplyImport } from './routes/apply'
import { Route as indexImport } from './routes/index'
import { Route as ApplicationIdImport } from './routes/application/$id'
import { Route as AdminLoginImport } from './routes/admin/login'
import { Route as AdminApplicationsImport } from './routes/admin/applications'
import { Route as AdminApplicationIdImport } from './routes/admin/application/$id'

// Create/Update Routes

const VerifyRoute = VerifyImport.update({
  path: '/verify',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const DashboardRoute = DashboardImport.update({
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const ApplyRoute = ApplyImport.update({
  path: '/apply',
  getParentRoute: () => rootRoute,
} as any)

const indexRoute = indexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ApplicationIdRoute = ApplicationIdImport.update({
  path: '/application/$id',
  getParentRoute: () => rootRoute,
} as any)

const AdminLoginRoute = AdminLoginImport.update({
  path: '/admin/login',
  getParentRoute: () => rootRoute,
} as any)

const AdminApplicationsRoute = AdminApplicationsImport.update({
  path: '/admin/applications',
  getParentRoute: () => rootRoute,
} as any)

const AdminApplicationIdRoute = AdminApplicationIdImport.update({
  path: '/admin/application/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof indexImport
      parentRoute: typeof rootRoute
    }
    '/admin/applications': {
      id: '/admin/applications'
      path: '/admin/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AdminApplicationsImport
      parentRoute: typeof rootRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginImport
      parentRoute: typeof rootRoute
    }
    '/application/$id': {
      id: '/application/$id'
      path: '/application/$id'
      fullPath: '/application/$id'
      preLoaderRoute: typeof ApplicationIdImport
      parentRoute: typeof rootRoute
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyImport
      parentRoute: typeof rootRoute
    }
    '/admin/application/$id': {
      id: '/admin/application/$id'
      path: '/admin/application/$id'
      fullPath: '/admin/application/$id'
      preLoaderRoute: typeof AdminApplicationIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  indexRoute,
  VerifyRoute,
  LoginRoute,
  DashboardRoute,
  ApplyRoute,
  ApplicationIdRoute,
  AdminLoginRoute,
  AdminApplicationsRoute,
  AdminApplicationIdRoute,
})

/* prettier-ignore-end */